<?php

/**
 * Implements hook_preprocess_html().
 *
 * Add styling class for type of website.
 */
function gb_site_controller_preprocess_html(&$variables) {
  $variables['attributes']['class'][] = 'griffin-brothers';
}

/**
 * Implements hook_page_attachments().
 */
function gb_site_controller_page_attachments(array &$page) {
  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();
  $is_node = \Drupal::routeMatch()->getRouteName();

  if ($is_admin || $is_node == 'layout_builder.overrides.node.view' || $is_node == 'entity.node.canonical') {
    $page['#attached']['library'][] = 'gb_site_controller/extra_admin';
    return;
  }
}
